/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Windows 10
 */

import java.util.ArrayList;
import java.util.Arrays;

public class BP1_M1_Tugas_IlhamHafidz extends javax.swing.JFrame {
    
    ArrayList<Integer> listTotalHarga = new ArrayList<Integer>();
    int total= 0;

    /**
     * Creates new form BP1_M1_Tugas_IlhamHafidz
     */
    public BP1_M1_Tugas_IlhamHafidz() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        rotiBakar = new javax.swing.JCheckBox();
        kebab = new javax.swing.JCheckBox();
        martabak = new javax.swing.JCheckBox();
        sosisGoreng = new javax.swing.JCheckBox();
        cireng = new javax.swing.JCheckBox();
        telorGulung = new javax.swing.JCheckBox();
        totalHarga = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        konfirmasiPesanan = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        totalBayar = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        kembalian = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        konfirmasiPesanan1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ILHAM STORE");
        jLabel1.setToolTipText("");

        rotiBakar.setText("Roti Bakar (Rp.10.000)");
        rotiBakar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rotiBakarMouseClicked(evt);
            }
        });
        rotiBakar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rotiBakarActionPerformed(evt);
            }
        });

        kebab.setText("Kebab (Rp 12.000)");
        kebab.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                kebabMouseClicked(evt);
            }
        });
        kebab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kebabActionPerformed(evt);
            }
        });

        martabak.setText("Martabak (RP 15.000)");
        martabak.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                martabakMouseClicked(evt);
            }
        });
        martabak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                martabakActionPerformed(evt);
            }
        });

        sosisGoreng.setText("Sosis Goreng (Rp 5.000)");
        sosisGoreng.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sosisGorengMouseClicked(evt);
            }
        });
        sosisGoreng.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sosisGorengActionPerformed(evt);
            }
        });

        cireng.setText("Cireng (Rp 3.000)");
        cireng.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cirengMouseClicked(evt);
            }
        });
        cireng.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cirengActionPerformed(evt);
            }
        });

        telorGulung.setText("Telor Gulung (Rp 1.000)");
        telorGulung.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                telorGulungMouseClicked(evt);
            }
        });
        telorGulung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                telorGulungActionPerformed(evt);
            }
        });

        totalHarga.setToolTipText("");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Total Harga :");

        konfirmasiPesanan.setText("Konfirmasi Pesanan");
        konfirmasiPesanan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                konfirmasiPesananMouseClicked(evt);
            }
        });
        konfirmasiPesanan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                konfirmasiPesananActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Total Bayar  : ");

        totalBayar.setToolTipText("");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Kembalian  : ");

        kembalian.setToolTipText("");

        konfirmasiPesanan1.setText("Konfirmasi Pembayaran");
        konfirmasiPesanan1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                konfirmasiPesanan1MouseClicked(evt);
            }
        });
        konfirmasiPesanan1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                konfirmasiPesanan1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rotiBakar)
                    .addComponent(martabak)
                    .addComponent(kebab))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sosisGoreng)
                    .addComponent(cireng)
                    .addComponent(telorGulung))
                .addGap(42, 42, 42))
            .addComponent(jSeparator1)
            .addComponent(jSeparator2)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(136, 136, 136)
                        .addComponent(konfirmasiPesanan))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(kembalian, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(totalHarga, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(64, 64, 64)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(totalBayar, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 18, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(konfirmasiPesanan1)
                .addGap(125, 125, 125))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rotiBakar)
                    .addComponent(sosisGoreng))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(martabak)
                    .addComponent(cireng))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kebab)
                    .addComponent(telorGulung))
                .addGap(31, 31, 31)
                .addComponent(konfirmasiPesanan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(totalBayar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(totalHarga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(konfirmasiPesanan1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kembalian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rotiBakarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rotiBakarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rotiBakarActionPerformed

    private void kebabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kebabActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kebabActionPerformed

    private void martabakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_martabakActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_martabakActionPerformed

    private void sosisGorengActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sosisGorengActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sosisGorengActionPerformed

    private void cirengActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cirengActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cirengActionPerformed

    private void telorGulungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_telorGulungActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_telorGulungActionPerformed

    private void rotiBakarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rotiBakarMouseClicked

        boolean ditemukan = false;

        for (int i = 0; i < listTotalHarga.size(); i++) {
            if (listTotalHarga.get(i) == 10000) {
                // Nilai 10000 ditemukan, hapus dari array
                listTotalHarga.remove(i);
                ditemukan = true;
                break; // Keluar dari loop setelah nilai ditemukan dan dihapus
            }
        }

        if (!ditemukan) {
            listTotalHarga.add(10000);
        }
    }//GEN-LAST:event_rotiBakarMouseClicked

    private void martabakMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_martabakMouseClicked
        boolean ditemukan = false;

        for (int i = 0; i < listTotalHarga.size(); i++) {
            if (listTotalHarga.get(i) == 15000) {
                // Nilai 10000 ditemukan, hapus dari array
                listTotalHarga.remove(i);
                ditemukan = true;
                break; // Keluar dari loop setelah nilai ditemukan dan dihapus
            }
        }

        if (!ditemukan) {
            listTotalHarga.add(15000);
        }
    }//GEN-LAST:event_martabakMouseClicked

    private void kebabMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kebabMouseClicked
        boolean ditemukan = false;

        for (int i = 0; i < listTotalHarga.size(); i++) {
            if (listTotalHarga.get(i) == 12000) {
                // Nilai 10000 ditemukan, hapus dari array
                listTotalHarga.remove(i);
                ditemukan = true;
                break; // Keluar dari loop setelah nilai ditemukan dan dihapus
            }
        }

        if (!ditemukan) {
            listTotalHarga.add(12000);
        }
    }//GEN-LAST:event_kebabMouseClicked

    private void sosisGorengMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sosisGorengMouseClicked
        boolean ditemukan = false;

        for (int i = 0; i < listTotalHarga.size(); i++) {
            if (listTotalHarga.get(i) == 5000) {
                // Nilai 10000 ditemukan, hapus dari array
                listTotalHarga.remove(i);
                ditemukan = true;
                break; // Keluar dari loop setelah nilai ditemukan dan dihapus
            }
        }

        if (!ditemukan) {
            listTotalHarga.add(5000);
        }
    }//GEN-LAST:event_sosisGorengMouseClicked

    private void cirengMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cirengMouseClicked
        boolean ditemukan = false;

        for (int i = 0; i < listTotalHarga.size(); i++) {
            if (listTotalHarga.get(i) == 3000) {
                // Nilai 10000 ditemukan, hapus dari array
                listTotalHarga.remove(i);
                ditemukan = true;
                break; // Keluar dari loop setelah nilai ditemukan dan dihapus
            }
        }

        if (!ditemukan) {
            listTotalHarga.add(3000);
        }
    }//GEN-LAST:event_cirengMouseClicked

    private void telorGulungMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_telorGulungMouseClicked
        boolean ditemukan = false;

        for (int i = 0; i < listTotalHarga.size(); i++) {
            if (listTotalHarga.get(i) == 1000) {
                // Nilai 10000 ditemukan, hapus dari array
                listTotalHarga.remove(i);
                ditemukan = true;
                break; // Keluar dari loop setelah nilai ditemukan dan dihapus
            }
        }

        if (!ditemukan) {
            listTotalHarga.add(1000);
        }
    }//GEN-LAST:event_telorGulungMouseClicked

    private void konfirmasiPesananActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_konfirmasiPesananActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_konfirmasiPesananActionPerformed

    private void konfirmasiPesananMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_konfirmasiPesananMouseClicked
        
        for (int i = 0; i < listTotalHarga.size(); i++) {
            total += listTotalHarga.get(i);
        }
        
        totalHarga.setText(String.valueOf(total));
    }//GEN-LAST:event_konfirmasiPesananMouseClicked

    private void konfirmasiPesanan1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_konfirmasiPesanan1MouseClicked
        String bayar = totalBayar.getText();
        int intBayar = Integer.parseInt(bayar);
        
        kembalian.setText(String.valueOf(intBayar - total));
    }//GEN-LAST:event_konfirmasiPesanan1MouseClicked

    private void konfirmasiPesanan1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_konfirmasiPesanan1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_konfirmasiPesanan1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BP1_M1_Tugas_IlhamHafidz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BP1_M1_Tugas_IlhamHafidz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BP1_M1_Tugas_IlhamHafidz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BP1_M1_Tugas_IlhamHafidz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BP1_M1_Tugas_IlhamHafidz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox cireng;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JCheckBox kebab;
    private javax.swing.JTextField kembalian;
    private javax.swing.JButton konfirmasiPesanan;
    private javax.swing.JButton konfirmasiPesanan1;
    private javax.swing.JCheckBox martabak;
    private javax.swing.JCheckBox rotiBakar;
    private javax.swing.JCheckBox sosisGoreng;
    private javax.swing.JCheckBox telorGulung;
    private javax.swing.JTextField totalBayar;
    private javax.swing.JTextField totalHarga;
    // End of variables declaration//GEN-END:variables
}
