/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

    import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
public class BP1_M3_Tugas_IlhamHafidz extends javax.swing.JFrame {

    /**
     * Creates new form BP1_M3_Tugas_IlhamHafidz
     */
    public BP1_M3_Tugas_IlhamHafidz() {
        initComponents();
        frameTambahMahasiswa.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jFrame1 = new javax.swing.JFrame();
        jFrame2 = new javax.swing.JFrame();
        jFrame3 = new javax.swing.JFrame();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jFrame4 = new javax.swing.JFrame();
        jFrame5 = new javax.swing.JFrame();
        jFrame6 = new javax.swing.JFrame();
        jFrame7 = new javax.swing.JFrame();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        frameTambahMahasiswa = new javax.swing.JInternalFrame();
        textFieldNama = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        textFieldKelas = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        textFieldSemester = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tombolSubmitDataMahasiswa = new javax.swing.JButton();
        cancelTambahDataMahasiswa = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuItemTambahDataMahasiswa = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        menuItemTambahDataMK = new javax.swing.JMenu();
        menuItemTambahDataMKTeori = new javax.swing.JMenuItem();
        menuItemTambahDataMKPraktikum = new javax.swing.JMenuItem();
        menuDataMahasiswa = new javax.swing.JMenu();
        menuItemFakultasKomputer = new javax.swing.JMenuItem();
        menuItemFakultasHukum = new javax.swing.JMenuItem();
        menuDataMK = new javax.swing.JMenu();
        menuItemTeori = new javax.swing.JMenuItem();
        meuItemPraktikum = new javax.swing.JMenuItem();
        menuDataNilai = new javax.swing.JMenu();
        menuItemUTS = new javax.swing.JMenuItem();
        menuItemUAS = new javax.swing.JMenuItem();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 218, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 138, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jFrame2Layout = new javax.swing.GroupLayout(jFrame2.getContentPane());
        jFrame2.getContentPane().setLayout(jFrame2Layout);
        jFrame2Layout.setHorizontalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame2Layout.setVerticalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jFrame3Layout = new javax.swing.GroupLayout(jFrame3.getContentPane());
        jFrame3.getContentPane().setLayout(jFrame3Layout);
        jFrame3Layout.setHorizontalGroup(
            jFrame3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame3Layout.setVerticalGroup(
            jFrame3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jFrame4Layout = new javax.swing.GroupLayout(jFrame4.getContentPane());
        jFrame4.getContentPane().setLayout(jFrame4Layout);
        jFrame4Layout.setHorizontalGroup(
            jFrame4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame4Layout.setVerticalGroup(
            jFrame4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jFrame5Layout = new javax.swing.GroupLayout(jFrame5.getContentPane());
        jFrame5.getContentPane().setLayout(jFrame5Layout);
        jFrame5Layout.setHorizontalGroup(
            jFrame5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame5Layout.setVerticalGroup(
            jFrame5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jFrame6Layout = new javax.swing.GroupLayout(jFrame6.getContentPane());
        jFrame6.getContentPane().setLayout(jFrame6Layout);
        jFrame6Layout.setHorizontalGroup(
            jFrame6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame6Layout.setVerticalGroup(
            jFrame6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jFrame7Layout = new javax.swing.GroupLayout(jFrame7.getContentPane());
        jFrame7.getContentPane().setLayout(jFrame7Layout);
        jFrame7Layout.setHorizontalGroup(
            jFrame7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame7Layout.setVerticalGroup(
            jFrame7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        jMenuItem2.setText("jMenuItem2");

        jMenuItem3.setText("jMenuItem3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        frameTambahMahasiswa.setVisible(true);

        jLabel1.setText("Nama");

        jLabel2.setText("Kelas");

        jLabel3.setText("Semester");

        tombolSubmitDataMahasiswa.setText("Submit");
        tombolSubmitDataMahasiswa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tombolSubmitDataMahasiswaMouseClicked(evt);
            }
        });

        cancelTambahDataMahasiswa.setText("Keluar");
        cancelTambahDataMahasiswa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cancelTambahDataMahasiswaMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout frameTambahMahasiswaLayout = new javax.swing.GroupLayout(frameTambahMahasiswa.getContentPane());
        frameTambahMahasiswa.getContentPane().setLayout(frameTambahMahasiswaLayout);
        frameTambahMahasiswaLayout.setHorizontalGroup(
            frameTambahMahasiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, frameTambahMahasiswaLayout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addGroup(frameTambahMahasiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(frameTambahMahasiswaLayout.createSequentialGroup()
                        .addComponent(cancelTambahDataMahasiswa, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(tombolSubmitDataMahasiswa))
                    .addGroup(frameTambahMahasiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(textFieldSemester, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(textFieldKelas, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(textFieldNama, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(20, 20, 20))
        );
        frameTambahMahasiswaLayout.setVerticalGroup(
            frameTambahMahasiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frameTambahMahasiswaLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textFieldNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textFieldKelas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textFieldSemester, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(frameTambahMahasiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tombolSubmitDataMahasiswa)
                    .addComponent(cancelTambahDataMahasiswa))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Ilham Hafidz", "TINFC-2022-01", "3"}
            },
            new String [] {
                "Nama", "Kelas", "Semester"
            }
        ));
        jScrollPane1.setViewportView(table);

        menuItemTambahDataMahasiswa.setText("File");
        menuItemTambahDataMahasiswa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemTambahDataMahasiswaActionPerformed(evt);
            }
        });

        jMenuItem1.setText("Tambah Data Mahasiswa");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        menuItemTambahDataMahasiswa.add(jMenuItem1);

        menuItemTambahDataMK.setText("Tambah Data MK");

        menuItemTambahDataMKTeori.setText("Teori");
        menuItemTambahDataMK.add(menuItemTambahDataMKTeori);

        menuItemTambahDataMKPraktikum.setText("Praktikum");
        menuItemTambahDataMK.add(menuItemTambahDataMKPraktikum);

        menuItemTambahDataMahasiswa.add(menuItemTambahDataMK);

        jMenuBar1.add(menuItemTambahDataMahasiswa);

        menuDataMahasiswa.setText("Data Mahasiswa");

        menuItemFakultasKomputer.setText("Fakultas Komputer");
        menuItemFakultasKomputer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemFakultasKomputerActionPerformed(evt);
            }
        });
        menuDataMahasiswa.add(menuItemFakultasKomputer);

        menuItemFakultasHukum.setText("Fakultas Hukum");
        menuDataMahasiswa.add(menuItemFakultasHukum);

        jMenuBar1.add(menuDataMahasiswa);

        menuDataMK.setText("Data MK");

        menuItemTeori.setText("Teori");
        menuItemTeori.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemTeoriActionPerformed(evt);
            }
        });
        menuDataMK.add(menuItemTeori);

        meuItemPraktikum.setText("Praktikum");
        meuItemPraktikum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                meuItemPraktikumActionPerformed(evt);
            }
        });
        menuDataMK.add(meuItemPraktikum);

        jMenuBar1.add(menuDataMK);

        menuDataNilai.setText("Data Nilai");

        menuItemUTS.setText("UTS");
        menuDataNilai.add(menuItemUTS);

        menuItemUAS.setText("UAS");
        menuDataNilai.add(menuItemUAS);

        jMenuBar1.add(menuDataNilai);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(66, 66, 66)
                .addComponent(frameTambahMahasiswa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(45, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(frameTambahMahasiswa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuItemFakultasKomputerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemFakultasKomputerActionPerformed

    }//GEN-LAST:event_menuItemFakultasKomputerActionPerformed

    private void menuItemTambahDataMahasiswaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemTambahDataMahasiswaActionPerformed

    }//GEN-LAST:event_menuItemTambahDataMahasiswaActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        frameTambahMahasiswa.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void tombolSubmitDataMahasiswaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tombolSubmitDataMahasiswaMouseClicked
        DefaultTableModel model = (DefaultTableModel) table.getModel(); // Mengambil model dari JTable
        Object[] rowData = {textFieldNama.getText(), textFieldKelas.getText(), textFieldSemester.getText()};
        model.addRow(rowData); 
        
        textFieldNama.setText("");
        textFieldKelas.setText("");
        textFieldSemester.setText("");
        
        JOptionPane.showMessageDialog(
                null, 
                "Berhasil menambah Data Mahasiswa", 
                "Information", 
                JOptionPane.INFORMATION_MESSAGE
        );
    }//GEN-LAST:event_tombolSubmitDataMahasiswaMouseClicked

    private void cancelTambahDataMahasiswaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelTambahDataMahasiswaMouseClicked
        frameTambahMahasiswa.setVisible(false);
    }//GEN-LAST:event_cancelTambahDataMahasiswaMouseClicked

    private void menuItemTeoriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemTeoriActionPerformed
        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Bahasa Pemrograman 1", "2"},
                {"Pemrograman Web", "2"},
                {"Matematika Diskrit", "3"},
                {"Aljabar Linear", "3"},
            },
            new String [] {
                "Nama Mata Kuliah", "SKS"
            }
        ));
    }//GEN-LAST:event_menuItemTeoriActionPerformed

    private void meuItemPraktikumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_meuItemPraktikumActionPerformed
        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Bahasa Pemrograman 1", "1"},
                {"Pemrograman Web", "1"},
                {"Sistem Operasi", "1"},
            },
            new String [] {
                "Nama Mata Kuliah", "SKS"
            }
        ));
    }//GEN-LAST:event_meuItemPraktikumActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BP1_M3_Tugas_IlhamHafidz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BP1_M3_Tugas_IlhamHafidz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BP1_M3_Tugas_IlhamHafidz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BP1_M3_Tugas_IlhamHafidz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BP1_M3_Tugas_IlhamHafidz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelTambahDataMahasiswa;
    private javax.swing.JInternalFrame frameTambahMahasiswa;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JFrame jFrame2;
    private javax.swing.JFrame jFrame3;
    private javax.swing.JFrame jFrame4;
    private javax.swing.JFrame jFrame5;
    private javax.swing.JFrame jFrame6;
    private javax.swing.JFrame jFrame7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenu menuDataMK;
    private javax.swing.JMenu menuDataMahasiswa;
    private javax.swing.JMenu menuDataNilai;
    private javax.swing.JMenuItem menuItemFakultasHukum;
    private javax.swing.JMenuItem menuItemFakultasKomputer;
    private javax.swing.JMenu menuItemTambahDataMK;
    private javax.swing.JMenuItem menuItemTambahDataMKPraktikum;
    private javax.swing.JMenuItem menuItemTambahDataMKTeori;
    private javax.swing.JMenu menuItemTambahDataMahasiswa;
    private javax.swing.JMenuItem menuItemTeori;
    private javax.swing.JMenuItem menuItemUAS;
    private javax.swing.JMenuItem menuItemUTS;
    private javax.swing.JMenuItem meuItemPraktikum;
    private javax.swing.JTable table;
    private javax.swing.JTextField textFieldKelas;
    private javax.swing.JTextField textFieldNama;
    private javax.swing.JTextField textFieldSemester;
    private javax.swing.JButton tombolSubmitDataMahasiswa;
    // End of variables declaration//GEN-END:variables
}
