import javax.swing.*;  

public class BP1_M3_P1_Ilham_Container extends javax.swing.JFrame {

    /**
     * Creates new form BP1_M3_P1_Ilham_Container
     */
    public BP1_M3_P1_Ilham_Container() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        tab = new javax.swing.JTabbedPane();
        panelDataMahasiswa = new javax.swing.JPanel();
        labelDataMahasiswa = new javax.swing.JLabel();
        panelDataMataKuliah = new javax.swing.JPanel();
        labelDataMatakuliah = new javax.swing.JLabel();
        panelDataNilai = new javax.swing.JPanel();
        labelDataNilai = new javax.swing.JLabel();

        jLabel2.setText("Ini tab data mahasiswa");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        labelDataMahasiswa.setText("Ini tab data mahasiswa");

        javax.swing.GroupLayout panelDataMahasiswaLayout = new javax.swing.GroupLayout(panelDataMahasiswa);
        panelDataMahasiswa.setLayout(panelDataMahasiswaLayout);
        panelDataMahasiswaLayout.setHorizontalGroup(
            panelDataMahasiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDataMahasiswaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelDataMahasiswa, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(263, Short.MAX_VALUE))
        );
        panelDataMahasiswaLayout.setVerticalGroup(
            panelDataMahasiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDataMahasiswaLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(labelDataMahasiswa)
                .addContainerGap(220, Short.MAX_VALUE))
        );

        tab.addTab("Data Mahasiswa", panelDataMahasiswa);

        labelDataMatakuliah.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelDataMatakuliah.setText("Ini tab data matakuliah");
        labelDataMatakuliah.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelDataMatakuliahMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelDataMataKuliahLayout = new javax.swing.GroupLayout(panelDataMataKuliah);
        panelDataMataKuliah.setLayout(panelDataMataKuliahLayout);
        panelDataMataKuliahLayout.setHorizontalGroup(
            panelDataMataKuliahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDataMataKuliahLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelDataMatakuliah, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelDataMataKuliahLayout.setVerticalGroup(
            panelDataMataKuliahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDataMataKuliahLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(labelDataMatakuliah)
                .addContainerGap(220, Short.MAX_VALUE))
        );

        tab.addTab("Data Matakuliah", panelDataMataKuliah);

        labelDataNilai.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelDataNilai.setText("Ini tab data nilai");

        javax.swing.GroupLayout panelDataNilaiLayout = new javax.swing.GroupLayout(panelDataNilai);
        panelDataNilai.setLayout(panelDataNilaiLayout);
        panelDataNilaiLayout.setHorizontalGroup(
            panelDataNilaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDataNilaiLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelDataNilai, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelDataNilaiLayout.setVerticalGroup(
            panelDataNilaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDataNilaiLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(labelDataNilai)
                .addContainerGap(220, Short.MAX_VALUE))
        );

        tab.addTab("Data Nilai", panelDataNilai);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tab)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tab)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void labelDataMatakuliahMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelDataMatakuliahMouseClicked
        int close = JOptionPane.showOptionDialog(this, "Ini tab Data Matakuliah, Keluar Aplikasi?",
                "YesNoOption", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null, null, null);
    }//GEN-LAST:event_labelDataMatakuliahMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BP1_M3_P1_Ilham_Container.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BP1_M3_P1_Ilham_Container.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BP1_M3_P1_Ilham_Container.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BP1_M3_P1_Ilham_Container.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BP1_M3_P1_Ilham_Container().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel labelDataMahasiswa;
    private javax.swing.JLabel labelDataMatakuliah;
    private javax.swing.JLabel labelDataNilai;
    private javax.swing.JPanel panelDataMahasiswa;
    private javax.swing.JPanel panelDataMataKuliah;
    private javax.swing.JPanel panelDataNilai;
    private javax.swing.JTabbedPane tab;
    // End of variables declaration//GEN-END:variables
}
