/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Windows 10
 */

import javax.swing.table.DefaultTableModel;

public class BP1_M3_PostTest1_IlhamHafidz extends javax.swing.JFrame {

    /**
     * Creates new form BP1_M3_PostTest1_IlhamHafidz
     */
    public BP1_M3_PostTest1_IlhamHafidz() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jScrollPane2 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuFile = new javax.swing.JMenu();
        menuItemFileOpen = new javax.swing.JMenuItem();
        menuItemFileSave = new javax.swing.JMenuItem();
        menuDataMahasiswa = new javax.swing.JMenu();
        menuItemFKOM = new javax.swing.JMenuItem();
        menuItemFH = new javax.swing.JMenuItem();
        menuDataMK = new javax.swing.JMenu();
        menuItemDataMKPWEB = new javax.swing.JMenuItem();
        menuItemDataMKBP = new javax.swing.JMenuItem();
        menuDataNilai = new javax.swing.JMenu();
        menuItemDataNilaiUTS = new javax.swing.JMenuItem();
        menuItemDataNilaiUAS = new javax.swing.JMenuItem();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Siti", "Pancasila", "80"},
                {"Budi", "Hukum Demokrasi", "70"}
            },
            new String [] {
                "Data Mahasiswa", "Data MK", "Data Nilai"
            }
        ));
        jScrollPane2.setViewportView(table);

        menuFile.setText("File");

        menuItemFileOpen.setText("Open");
        menuItemFileOpen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemFileOpenActionPerformed(evt);
            }
        });
        menuFile.add(menuItemFileOpen);

        menuItemFileSave.setText("Save");
        menuFile.add(menuItemFileSave);

        jMenuBar1.add(menuFile);

        menuDataMahasiswa.setText("Data Mahasiswa");
        menuDataMahasiswa.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                menuDataMahasiswaItemStateChanged(evt);
            }
        });
        menuDataMahasiswa.addHierarchyListener(new java.awt.event.HierarchyListener() {
            public void hierarchyChanged(java.awt.event.HierarchyEvent evt) {
                menuDataMahasiswaHierarchyChanged(evt);
            }
        });
        menuDataMahasiswa.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                menuDataMahasiswaMenuSelected(evt);
            }
        });

        menuItemFKOM.setText("Fakultas Komputer");
        menuItemFKOM.addMenuKeyListener(new javax.swing.event.MenuKeyListener() {
            public void menuKeyPressed(javax.swing.event.MenuKeyEvent evt) {
                menuItemFKOMMenuKeyPressed(evt);
            }
            public void menuKeyReleased(javax.swing.event.MenuKeyEvent evt) {
            }
            public void menuKeyTyped(javax.swing.event.MenuKeyEvent evt) {
            }
        });
        menuItemFKOM.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                menuItemFKOMStateChanged(evt);
            }
        });
        menuItemFKOM.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuItemFKOMMouseClicked(evt);
            }
        });
        menuItemFKOM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemFKOMActionPerformed(evt);
            }
        });
        menuDataMahasiswa.add(menuItemFKOM);

        menuItemFH.setText("Fakultas Hukum");
        menuItemFH.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuItemFHMouseClicked(evt);
            }
        });
        menuItemFH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemFHActionPerformed(evt);
            }
        });
        menuDataMahasiswa.add(menuItemFH);

        jMenuBar1.add(menuDataMahasiswa);

        menuDataMK.setText("Data MK");
        menuDataMK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuDataMKActionPerformed(evt);
            }
        });

        menuItemDataMKPWEB.setText("Pemrograman Web");
        menuItemDataMKPWEB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemDataMKPWEBActionPerformed(evt);
            }
        });
        menuDataMK.add(menuItemDataMKPWEB);

        menuItemDataMKBP.setText("Bahasa Pemrograman");
        menuItemDataMKBP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemDataMKBPActionPerformed(evt);
            }
        });
        menuDataMK.add(menuItemDataMKBP);

        jMenuBar1.add(menuDataMK);

        menuDataNilai.setText("Data Nilai");

        menuItemDataNilaiUTS.setText("Nilai UTS");
        menuDataNilai.add(menuItemDataNilaiUTS);

        menuItemDataNilaiUAS.setText("Nilai UAS");
        menuDataNilai.add(menuItemDataNilaiUAS);

        jMenuBar1.add(menuDataNilai);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(57, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuItemFHMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuItemFHMouseClicked
       
    }//GEN-LAST:event_menuItemFHMouseClicked

    private void menuItemFKOMMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuItemFKOMMouseClicked
        
    }//GEN-LAST:event_menuItemFKOMMouseClicked

    private void menuDataMahasiswaHierarchyChanged(java.awt.event.HierarchyEvent evt) {//GEN-FIRST:event_menuDataMahasiswaHierarchyChanged

    }//GEN-LAST:event_menuDataMahasiswaHierarchyChanged

    private void menuDataMahasiswaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_menuDataMahasiswaItemStateChanged

    }//GEN-LAST:event_menuDataMahasiswaItemStateChanged

    private void menuDataMahasiswaMenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_menuDataMahasiswaMenuSelected
        
    }//GEN-LAST:event_menuDataMahasiswaMenuSelected

    private void menuItemFKOMMenuKeyPressed(javax.swing.event.MenuKeyEvent evt) {//GEN-FIRST:event_menuItemFKOMMenuKeyPressed
        
    }//GEN-LAST:event_menuItemFKOMMenuKeyPressed

    private void menuItemFKOMStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_menuItemFKOMStateChanged
        
    }//GEN-LAST:event_menuItemFKOMStateChanged

    private void menuItemFKOMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemFKOMActionPerformed
        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Ilham", "Pemrogramman Web", "100"},
                {"Hafidz", "Bahasa Programan", "90"},
            },
            new String [] {
                "Data Mahasiswa", "Data MK", "Data Nilai"
            }
        ));
    }//GEN-LAST:event_menuItemFKOMActionPerformed

    private void menuItemFHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemFHActionPerformed
        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Siti", "Pancasila", "80"},
                {"Budi", "Hukum Demokrasi", "70"},
            },
            new String [] {
                "Data Mahasiswa", "Data MK", "Data Nilai"
            }
        ));
    }//GEN-LAST:event_menuItemFHActionPerformed

    private void menuItemFileOpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemFileOpenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuItemFileOpenActionPerformed

    private void menuDataMKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuDataMKActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuDataMKActionPerformed

    private void menuItemDataMKPWEBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemDataMKPWEBActionPerformed
        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"1", "HTML"},
                {"2", "CSS & Bootstrap"},
            },
            new String [] {
                "Modul", "Judul"
            }
        ));
    }//GEN-LAST:event_menuItemDataMKPWEBActionPerformed

    private void menuItemDataMKBPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemDataMKBPActionPerformed
        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"1", "AWT"},
                {"2", "Applet"},
            },
            new String [] {
                "Modul", "Judul"
            }
        ));
    }//GEN-LAST:event_menuItemDataMKBPActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BP1_M3_PostTest1_IlhamHafidz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BP1_M3_PostTest1_IlhamHafidz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BP1_M3_PostTest1_IlhamHafidz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BP1_M3_PostTest1_IlhamHafidz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BP1_M3_PostTest1_IlhamHafidz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFrame jFrame1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JMenu menuDataMK;
    private javax.swing.JMenu menuDataMahasiswa;
    private javax.swing.JMenu menuDataNilai;
    private javax.swing.JMenu menuFile;
    private javax.swing.JMenuItem menuItemDataMKBP;
    private javax.swing.JMenuItem menuItemDataMKPWEB;
    private javax.swing.JMenuItem menuItemDataNilaiUAS;
    private javax.swing.JMenuItem menuItemDataNilaiUTS;
    private javax.swing.JMenuItem menuItemFH;
    private javax.swing.JMenuItem menuItemFKOM;
    private javax.swing.JMenuItem menuItemFileOpen;
    private javax.swing.JMenuItem menuItemFileSave;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables
}
